Repository fga-eps-mds/2019.1-ADA-gitlab, pull requests merged in 2019-06, with the labels that each got.

#29 #255 Atualizar readme
  .gitlab-ci.yml
  README.md
  api/gitlab/tests/test_gitlab_utils.py
  api/gitlab/tests/test_webhook.py
  api/gitlab/user/views.py
  api/gitlab/webhook/error_messages.py
  api/gitlab/webhook/utils.py
  api/gitlab/webhook/views.py
  docker-compose-dev.yml
  env_vars.md
Labels: DevOps

#27 #254 Cadastrar repo de organizacoes
  api/gitlab/tests/test_user.py
  api/gitlab/user/utils.py
  api/gitlab/user/views.py
  api/gitlab/utils/gitlab_utils.py
Labels: enhancement

#30 #265 Melhoria no fluxo de conversa
  CONTRIBUTING.md
  README.md
  api/gitlab/user/utils.py
  docker-compose.yml
Labels: bug

#21 US24 - Eu, como usuário, desejo que a Ada configure no pipeline de deploy a última versão estável do repositório para recolocar o serviço no ar.
  api/gitlab/__init__.py
  api/gitlab/stable_deploy/__init__.py
  api/gitlab/stable_deploy/error_messages.py
  api/gitlab/stable_deploy/stable_deploy_utils.py
  api/gitlab/stable_deploy/views.py
  api/gitlab/tests/jsonschemas/stable_deploy/__init__.py
  api/gitlab/tests/jsonschemas/stable_deploy/schemas.py
  api/gitlab/tests/test_stable_deploy.py
Labels: enhancement

#32 Configuração do cronjob
  .gitignore
  .gitlab-ci.yml
  api/gitlab/cronjob/crontab
  api/gitlab/cronjob/scripts/__init__.py
  api/gitlab/cronjob/scripts/monitoring_domain.py
  api/gitlab/data/project.py
  api/gitlab/data/user.py
  api/gitlab/pipeline/views.py
  cronjob/crontab
  cronjob/entrypoint_cron.sh
  cronjob/env_loader.py
  cronjob/monitoring_domain.py
  cronjob/update_project_model.sh
  cronjob/update_user_model.sh
  docker-compose.yml
  docker/cronjob.Dockerfile
  docker/cronjob.requirements.txt
  docker/dev.Dockerfile
Labels: DevOps
